import { generateDemoCode, generateDemoPin } from "./order";

/**
 * Fulfillment is intentionally behind an interface. DemoGiftCardProvider
 * below issues random, NON-REDEEMABLE placeholder codes — it exists so the
 * checkout/order/email flow can be built and tested end-to-end before a real
 * supplier contract is in place.
 *
 * TangoCardProvider (below) implements this against Tango Card's RaaS API.
 * It activates automatically once TANGO_PLATFORM_NAME / TANGO_PLATFORM_KEY /
 * TANGO_ACCOUNT_IDENTIFIER / TANGO_CUSTOMER_IDENTIFIER are all set — see
 * .env.example. Until then, DemoGiftCardProvider stays active. Do not point
 * real Stripe charges at DemoGiftCardProvider — customers would pay for
 * codes that don't work.
 */
export type IssuedCard = { code: string; pin: string; isDemo: boolean };

export interface GiftCardProvider {
  issue(params: { brandSlug: string; amountCents: number }): Promise<IssuedCard>;
}

export class DemoGiftCardProvider implements GiftCardProvider {
  async issue(): Promise<IssuedCard> {
    return { code: generateDemoCode(), pin: generateDemoPin(), isDemo: true };
  }
}

/**
 * Tango Card RaaS (Rewards-as-a-Service) API.
 *
 * Verified end-to-end against a real sandbox order (2026-08-30): fetched
 * the live catalog, placed a real order (Starbucks, $5, orderStatus
 * COMPLETE), and confirmed the actual credential response shape — which
 * differs by brand. The credentialList parsing below and the utids in
 * BRAND_TO_TANGO_UTID are from that verified response, not guessed from
 * docs. Still true before taking real payments through it:
 *   1. This only covers the ~66 brands present in your sandbox's "Public
 *      Test Catalog" — get production catalog access once your Tango
 *      agreement is finalized and re-run `npm run tango:match` for the rest.
 *   2. TANGO_ACCOUNT_IDENTIFIER / TANGO_CUSTOMER_IDENTIFIER must be a real
 *      funded account + registered customer in your Tango account — `GET
 *      /accounts` and `GET /customers` list what's available.
 *   3. Switch TANGO_API_BASE_URL to the production host and re-verify
 *      before ever pointing this at live Stripe keys.
 */

// Maps our internal brand slugs (src/lib/brands.ts) to Tango Card's "utid"
// (unique Tango ID). Two shapes:
//   - string: a variable-value card — one utid accepts any dollar amount.
//   - { [dollars]: utid }: a fixed-value card — Tango issues a specific
//     denomination per utid, so the exact amount must be mapped or the
//     order fails loudly rather than silently shipping the wrong value.
// These are specific to your Tango account and NOT guessable; populate via
// `npm run tango:match` (scripts/match-tango-catalog.mjs) once you have
// sandbox credentials. Brands with no entry here throw when issued.
// Generated by `npm run tango:match` against your sandbox account's
// "Public Test Catalog" — a curated subset for testing, not Tango's full
// real-world catalog (it also contains synthetic entries like "Always
// Fail" and "Always successful CV test brand"). Big brands not appearing
// here (Visa, Amazon, Nike, Target, McDonald's, etc.) are very likely just
// not offered in this sandbox catalog, not a matching failure — re-run
// this once you have production catalog access to fill in the rest.
export const BRAND_TO_TANGO_UTID: Record<string, string | Record<number, string>> = {
  starbucks: "U761382",
  doordash: "U964209",
  uber: "U552132",
  steam: { 20: "U128267" },
  airbnb: "U986050",
  walmart: "U640032",
  panera: "U455508",
  xbox: { 100: "U635195", 15: "U533358", 25: "U684145", 50: "U554576" },
  ubereats: "U517295",
  lowes: "U589797",
  adidas: "U561621",
  autozone: "U605768",
  advanceautoparts: { 10: "U421313", 100: "U757661", 25: "U360639", 50: "U021383" },
  jiffylube: "U909478",
  cvspharmacy: { 10: "U922376", 100: "U057891", 25: "U105443", 5: "U029039", 50: "U360814" },
  bathbodyworks: "U728067",
  saks: "U574235",
  macys: { 10: "U814874", 100: "U154340", 25: "U002285", 5: "U452033", 50: "U010277" },
  staples: "U054405",
  containerstore: "U939746",
  totalwine: "U481673",
  jcpenney: { 10: "U957067", 100: "U055714", 25: "U424837", 5: "U333200", 50: "U420399" },
  shutterfly: { 25: "U034114", 50: "U159838" },
  groupon: "U513938",
  underarmour: "U396551",
  gamestop: { 10: "U008738", 100: "U606897", 20: "U134841", 30: "U261536", 50: "U882261" },
  llbean: "U020624",
  dsw: { 100: "U266243", 25: "U497669", 50: "U942465" },
  chicos: "U506551",
  boscovs: "U747187",
  aeo: "U094392",
  carters: "U448010",
  stitchfix: "U633671",
  subway: "U835764",
  darden: "U516600",
  dominos: "U012700",
  bjsrestaurants: "U254643",
  chilis: "U714697",
  grubhub: "U407739",
  krispykreme: "U774099",
  olivegarden: "U009367",
  outback: "U020421",
  applebees: "U291543",
  burgerking: "U414456",
  planetsmoothie: "U260455",
  sweetfrog: { 10: "U911418", 25: "U699112", 5: "U923701" },
  bubbagump: "U664253",
  carrabbas: "U667894",
  bahamabreeze: "U498786",
  rubytuesday: "U479635",
  seasons52: "U446590",
  longhornsteakhouse: "U501409",
  omahasteaks: "U019801",
  buffalowildwings: "U203426",
  southwest: "U557938",
  amctheatres: { 10: "U154092" },
  regal: "U209942",
  cinemark: { 25: "U828533", 50: "U472558" },
  spafinder: "U477356",
  fanatics: { 100: "U789465", 25: "U080019", 50: "U883973" },
  basspro: "U318911",
  petco: "U469706",
  chewy: "U799664",
  barnesnoble: "U049172",
  gap: "U053802",
  hellofresh: { 100: "U238418" },
};

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is not set — required for TangoCardProvider`);
  return value;
}

export class TangoCardProvider implements GiftCardProvider {
  private baseUrl: string;
  private platformName: string;
  private platformKey: string;
  private accountIdentifier: string;
  private customerIdentifier: string;

  constructor() {
    // Sandbox vs production is just a different base URL in Tango's API —
    // defaults to sandbox so you can't accidentally hit production by
    // forgetting to set this.
    this.baseUrl = process.env.TANGO_API_BASE_URL || "https://integration-api.tangocard.com/raas/v2";
    this.platformName = requireEnv("TANGO_PLATFORM_NAME");
    this.platformKey = requireEnv("TANGO_PLATFORM_KEY");
    this.accountIdentifier = requireEnv("TANGO_ACCOUNT_IDENTIFIER");
    this.customerIdentifier = requireEnv("TANGO_CUSTOMER_IDENTIFIER");
  }

  async issue({ brandSlug, amountCents }: { brandSlug: string; amountCents: number }): Promise<IssuedCard> {
    const mapping = BRAND_TO_TANGO_UTID[brandSlug];
    if (!mapping) {
      throw new Error(
        `No Tango Card utid mapped for brand "${brandSlug}". Run \`npm run tango:match\` and add it to BRAND_TO_TANGO_UTID.`
      );
    }

    let utid: string;
    if (typeof mapping === "string") {
      utid = mapping; // variable-value card, works for any amount
    } else {
      const dollars = amountCents / 100;
      const found = mapping[dollars];
      if (!found) {
        throw new Error(
          `Brand "${brandSlug}" has no Tango utid for $${dollars} — available: ${Object.keys(mapping).join(", ")}`
        );
      }
      utid = found;
    }

    const auth = Buffer.from(`${this.platformName}:${this.platformKey}`).toString("base64");
    const res = await fetch(`${this.baseUrl}/orders`, {
      method: "POST",
      headers: {
        Authorization: `Basic ${auth}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        accountIdentifier: this.accountIdentifier,
        customerIdentifier: this.customerIdentifier,
        amount: amountCents / 100,
        utid,
        sendEmail: false, // we deliver the code ourselves via our own email
      }),
    });

    if (!res.ok) {
      const body = await res.text().catch(() => "");
      throw new Error(`Tango Card order failed (${res.status}): ${body}`);
    }

    const data = await res.json();
    // Verified against a real sandbox order (Starbucks, $5): the response
    // has reward.credentialList = [{ label, value, type, credentialType }],
    // and credentialType varies by brand/reward — card-number brands use
    // "cardNumber"/"pin", others (confirmed: Starbucks) deliver a
    // "redemptionUrl" instead with no PIN at all. Handle both rather than
    // assuming one shape.
    type Credential = { credentialType?: string; value?: string };
    const credentialList: Credential[] = data?.reward?.credentialList ?? [];

    const cardNumber = credentialList.find((c) => c.credentialType === "cardNumber")?.value;
    const pin = credentialList.find((c) => c.credentialType === "pin")?.value ?? "";
    const redemptionUrl = credentialList.find(
      (c) => c.credentialType === "redemptionUrl" || c.credentialType === "claimUrl"
    )?.value;

    const code = cardNumber ?? redemptionUrl ?? credentialList[0]?.value;
    if (!code) {
      throw new Error(`Tango Card order succeeded but no redeemable code was found in the response: ${JSON.stringify(data)}`);
    }

    return { code, pin, isDemo: false };
  }
}

// Per-brand, not global: only ~66 of our 165 catalog brands have a Tango
// utid mapped (sandbox catalog is a curated subset — see the comment on
// BRAND_TO_TANGO_UTID). A single global switch would mean checkout starts
// throwing entirely for every unmapped brand the moment Tango is
// configured. Instead: use Tango when a brand is mapped, fall back to Demo
// (loudly logged) when it isn't — the resulting code is still marked
// isDemo, which the order detail page and email already surface clearly.
class HybridGiftCardProvider implements GiftCardProvider {
  constructor(
    private tango: GiftCardProvider,
    private demo: GiftCardProvider
  ) {}

  async issue(params: { brandSlug: string; amountCents: number }): Promise<IssuedCard> {
    if (BRAND_TO_TANGO_UTID[params.brandSlug]) {
      return this.tango.issue(params);
    }
    console.warn(
      `[giftcard-provider] "${params.brandSlug}" has no Tango mapping — issuing a non-redeemable demo code instead of real fulfillment.`
    );
    return this.demo.issue(params);
  }
}

function buildProvider(): GiftCardProvider {
  const hasTangoConfig =
    process.env.TANGO_PLATFORM_NAME &&
    process.env.TANGO_PLATFORM_KEY &&
    process.env.TANGO_ACCOUNT_IDENTIFIER &&
    process.env.TANGO_CUSTOMER_IDENTIFIER;

  if (hasTangoConfig) {
    console.log(
      `[giftcard-provider] Using TangoCardProvider for ${Object.keys(BRAND_TO_TANGO_UTID).length} mapped brands, DemoGiftCardProvider fallback for the rest`
    );
    return new HybridGiftCardProvider(new TangoCardProvider(), new DemoGiftCardProvider());
  }
  console.warn("[giftcard-provider] Tango Card env vars not set — using DemoGiftCardProvider (non-redeemable codes)");
  return new DemoGiftCardProvider();
}

export const giftCardProvider: GiftCardProvider = buildProvider();
